# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: webhoanhao
google_analytics: UA-106150242-1
title: Web Hoàn Hảo

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Web Hoàn Hảo
description: Blog của Web Hoàn Hảo

author:
  name: Web Hoan Hao
  email: webhoanhao@gmail.com
  github: webhoanhao
  twitter: webhoanhao
  pinterest: webhoanhao
  linkedin: webhoanhao
  bio: Nếu bộ nhớ của bạn không đủ, hãy để blog nhớ dùm !
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

gems:
  - jekyll-paginate
